### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by michelepra** [clux/sdp-transform#65]
is possible to add typescript definition?

**Comment by afrokick** [comment]
http://npmjs.com/package/@types/sdp-transform

**Comment by ibc** [comment]
I should have checked this before doing https://github.com/clux/sdp-transform/tree/typescript. 

BTW who does maintain those `sdp-transform` typescript definitions?

I think we can close this issue since having to install `@types/xxxxx` is a common pattern, although I'll modify my PR to just document it.
