### ISSUE TITLE
Single file release for in-browser use

### ISSUE THREAD

**Issue by lostmsu** [clux/sdp-transform#99]
_consider this a rant_

I am building a full stack app that also has desktop components all the way down to native code and code patching to capture video.

As such I am allergic to 100500 build systems used at all layers, and NPM with Webpack are of the most annoying ones for oh so many reasons.

Can I please have a prepacked single .js file of the latest release I could copy to my SPA and import as a ES6 module? The only thing I ever needed was to know if my SDP answer has `a=inactive` for the video stream. 😭

**Comment by ibc** [comment]
You are requesting something because AFAIU this library fails to be imported when using webpack.  It shouldn't fail unless webpack is doing wrong assumptions, and I'm pretty sure that webpack is able to import this library. If not, please dig into the problem and, if you figure out it's related to this library, then report a proper issue.

Other than that I suggest the author @clux to close this ticket since having to provide with a bundled single JS file is not the way to go anymore in modern JS development.

**Comment by clux** [comment]
[THE SOFTWARE IS PROVIDED 'AS IS'](https://github.com/clux/sdp-transform/blob/master/LICENSE#L16C1-L16C62).

Explicit suggestions are of course welcome, but this is unproductive.
